apiVersion: apps/v1
kind: Deployment
metadata:
  name: projects-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: projects
  template:
    metadata:
      labels:
        app: projects
    spec:
      containers:
      - name: projects
        image: zigxi/projects:latest
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: projects-service
spec:
  selector:
    app: projects
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer
